//! The tray icon: the one part of this program that lives outside its window.
//!
//! It exists because of one exit mode. "Keep running in the background" takes the
//! window away and leaves the program managing the profiles, and without a tray
//! icon that state would be invisible: no window, no way back but the taskbar, and
//! no way to leave at all except the window's own Quit button - which is the thing
//! the user just put away.
//!
//! Two implementations, because the platforms have nothing in common here:
//!
//! - **Linux** is a StatusNotifierItem over D-Bus, through `ksni`. It is pure Rust
//!   (`zbus`), so this does not add GTK or libappindicator to the build or to the
//!   packages, and the service runs on a thread of its own.
//! - **Windows** is the notification area, through `tray-icon`. The icon is created
//!   on this thread and its messages are dispatched by the message loop the window
//!   already runs, so there is no second pump to write. That is also why the
//!   dependency is Windows-only: the same crate's Linux half wants GTK, and the
//!   Linux half here is `ksni`.
//!
//! Both reduce to the same two requests, and neither calls into the window from the
//! thread that noticed the click: an event goes into a queue and the window's tick
//! picks it up, which is what the runtime events already do.

use crate::text::Text;

// The pixels are generated by `scripts/make-icon.py` along with the icon and the
// SVG, so there is one design and one thing that draws it. See that file for why
// the asset is committed at all.
const PIXELS: &[u8] = include_bytes!("../../../assets/tray.rgba");
const SIDE: u32 = 64;

/// What the tray asks the window to do.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayEvent {
    /// Bring the window back. A left click on the icon, or the menu's first item.
    Show,
    /// Leave, and stop everything this program started. Deliberately not a mode
    /// and deliberately not the remembered answer: a tray whose only way out
    /// re-entered "keep running" would be a program nobody could quit, and one
    /// that left the browsers behind would be a menu item that says "quit" and
    /// does not.
    Quit,
}

/// How a window starts its tray icon.
///
/// A function pointer rather than a direct call to [`Tray::start`], for the same
/// reason the verifier, the tester, the opener and the copier are injected: the
/// interesting case is the desktop that refuses the icon, and the decision that
/// hangs on it - whether the window may be hidden at all - has to be reachable
/// from a test. A pointer rather than a trait object because there is no state to
/// carry.
pub type TrayStarter = fn(&'static Text) -> Result<Tray, String>;

/// A live tray icon, and the requests it has collected.
pub struct Tray {
    backend: TrayBackend,
}

enum TrayBackend {
    Live(Backend),
    #[cfg(test)]
    Fake(crossbeam_channel::Receiver<TrayEvent>),
}

impl Tray {
    /// Puts the icon in the tray.
    ///
    /// Failing is not fatal and must not be: a desktop without a StatusNotifierItem
    /// host, or a Windows shell that is not running, means "keep running" has no
    /// way back - which is worth a warning, not a refusal to keep running. The
    /// caller decides; the error is the sentence.
    pub fn start(t: &'static Text) -> Result<Self, String> {
        Ok(Self {
            backend: TrayBackend::Live(Backend::start(t)?),
        })
    }

    /// Takes everything the user has asked for since the last look.
    pub fn drain(&self) -> Vec<TrayEvent> {
        match &self.backend {
            TrayBackend::Live(backend) => backend.drain(),
            #[cfg(test)]
            TrayBackend::Fake(events) => events.try_iter().collect(),
        }
    }
}

#[cfg(test)]
pub(crate) mod testing {
    use super::*;

    /// A starter that succeeds without touching the desktop or session bus.
    pub fn fake_starter(_: &'static Text) -> Result<Tray, String> {
        let (_sender, receiver) = crossbeam_channel::unbounded();
        Ok(Tray {
            backend: TrayBackend::Fake(receiver),
        })
    }

    /// Creates a fake tray along with a sender to simulate tray events in tests.
    pub fn fake_tray() -> (Tray, crossbeam_channel::Sender<TrayEvent>) {
        let (sender, receiver) = crossbeam_channel::unbounded();
        (
            Tray {
                backend: TrayBackend::Fake(receiver),
            },
            sender,
        )
    }
}

#[cfg(target_os = "linux")]
use linux::Backend;

/// A StatusNotifierItem over D-Bus.
#[cfg(target_os = "linux")]
mod linux {
    use super::{PIXELS, SIDE, TrayEvent};
    use crate::text::Text;
    use crossbeam_channel::{Receiver, Sender};
    use ksni::blocking::{Handle, TrayMethods};

    pub(super) struct Backend {
        events: Receiver<TrayEvent>,
        /// The service owns its thread and the icon; this handle is how the icon
        /// would be withdrawn, and dropping it with the process is the ordinary
        /// way this ends.
        _handle: Handle<StatusIcon>,
    }

    impl Backend {
        pub(super) fn start(t: &'static Text) -> Result<Self, String> {
            let (sender, events) = crossbeam_channel::unbounded();
            let icon = StatusIcon {
                events: sender,
                show: t.tray_show,
                quit: t.tray_quit,
                title: crate::version::NAME.to_string(),
            };
            // Registering on the session bus is the part that fails when there is
            // no desktop to register with, and that is the whole error.
            let handle = icon.spawn().map_err(|error| error.to_string())?;
            Ok(Self {
                events,
                _handle: handle,
            })
        }

        pub(super) fn drain(&self) -> Vec<TrayEvent> {
            self.events.try_iter().collect()
        }
    }

    struct StatusIcon {
        events: Sender<TrayEvent>,
        show: &'static str,
        quit: &'static str,
        title: String,
    }

    impl ksni::Tray for StatusIcon {
        fn id(&self) -> String {
            "fingerprint-browser".to_string()
        }

        fn title(&self) -> String {
            self.title.clone()
        }

        fn icon_pixmap(&self) -> Vec<ksni::Icon> {
            vec![argb_icon()]
        }

        /// What a hover shows. The default is an empty tooltip, which on some
        /// hosts is a hover that says nothing at all.
        fn tool_tip(&self) -> ksni::ToolTip {
            ksni::ToolTip {
                title: self.title.clone(),
                ..Default::default()
            }
        }

        /// A left click on the icon itself, which is what a tray icon is for.
        fn activate(&mut self, _x: i32, _y: i32) {
            let _ = self.events.send(TrayEvent::Show);
        }

        fn menu(&self) -> Vec<ksni::MenuItem<Self>> {
            use ksni::menu::StandardItem;
            // The callbacks run on the D-Bus thread and must not block or reach
            // into the window, so they only post. An unbounded send is not a
            // blocking operation.
            let show = self.events.clone();
            let quit = self.events.clone();
            vec![
                StandardItem {
                    label: self.show.to_string(),
                    activate: Box::new(move |_| {
                        let _ = show.send(TrayEvent::Show);
                    }),
                    ..Default::default()
                }
                .into(),
                StandardItem {
                    label: self.quit.to_string(),
                    activate: Box::new(move |_| {
                        let _ = quit.send(TrayEvent::Quit);
                    }),
                    ..Default::default()
                }
                .into(),
            ]
        }
    }

    /// The icon in ARGB32, which is what the specification asks for and what the
    /// asset is not: one drawing, two byte orders, swapped here rather than
    /// committed twice.
    fn argb_icon() -> ksni::Icon {
        // `as_chunks` rather than `chunks_exact(4)`: the asset is a whole number
        // of four-byte pixels, and saying so once here means every `pixel` below
        // is a `[u8; 4]` the compiler can index, rather than a slice whose length
        // each read has to trust.
        let (pixels, _) = PIXELS.as_chunks::<4>();
        let mut data = Vec::with_capacity(PIXELS.len());
        for &[red, green, blue, alpha] in pixels {
            data.extend_from_slice(&[alpha, red, green, blue]);
        }
        ksni::Icon {
            width: SIDE as i32,
            height: SIDE as i32,
            data,
        }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        /// The specification asks for ARGB32 in network byte order and the asset
        /// is RGBA, so this is the one part of the tray that a desktop cannot
        /// check: a swapped order is a plausible icon in the wrong colours, which
        /// reads as a design mistake rather than a bug.
        #[test]
        fn the_icon_is_argb_with_the_alpha_first() {
            let icon = argb_icon();
            assert_eq!(icon.width, SIDE as i32);
            assert_eq!(icon.height, SIDE as i32);
            assert_eq!(icon.data.len(), PIXELS.len());

            let at = |pixels: &[u8], index: usize| pixels[index * 4..index * 4 + 4].to_vec();
            // A transparent corner is black in both orders, so the pixel that
            // means something here is an opaque one.
            let (pixels, _) = PIXELS.as_chunks::<4>();
            let opaque = pixels
                .iter()
                .position(|pixel| pixel[3] == 255)
                .expect("the icon has opaque pixels");
            let rgba = at(PIXELS, opaque);
            assert_eq!(at(&icon.data, opaque), [rgba[3], rgba[0], rgba[1], rgba[2]]);
        }

        /// The live check, and the only one that can fail for a reason that is not
        /// this program's: registering with a desktop's notification host.
        #[test]
        #[ignore = "requires a desktop session with a StatusNotifierItem host"]
        fn the_tray_registers_with_the_desktops_notification_host() {
            let tray = crate::tray::Tray::start(crate::text::en())
                .expect("a session bus should take the icon");
            assert!(tray.drain().is_empty(), "nothing has been clicked yet");
        }
    }
}

#[cfg(windows)]
use windows::Backend;

/// The shell's notification area.
#[cfg(windows)]
mod windows {
    use super::{PIXELS, SIDE, TrayEvent};
    use crate::text::Text;
    use tray_icon::menu::{Menu, MenuEvent, MenuItem};
    use tray_icon::{
        Icon, MouseButton, MouseButtonState, TrayIcon, TrayIconAttributes, TrayIconEvent,
    };

    /// The ids the two items are recognized by. They are not shown to anyone.
    const SHOW: &str = "show-window";
    const QUIT: &str = "quit";

    pub(super) struct Backend {
        /// Dropping this takes the icon out of the notification area, which is
        /// what should happen when the program ends.
        _icon: TrayIcon,
    }

    impl Backend {
        pub(super) fn start(t: &'static Text) -> Result<Self, String> {
            let menu = Menu::new();
            menu.append_items(&[
                &MenuItem::with_id(SHOW, t.tray_show, true, None),
                &MenuItem::with_id(QUIT, t.tray_quit, true, None),
            ])
            .map_err(|error| error.to_string())?;
            let icon =
                Icon::from_rgba(PIXELS.to_vec(), SIDE, SIDE).map_err(|error| error.to_string())?;
            let icon = TrayIcon::new(TrayIconAttributes {
                icon: Some(icon),
                menu: Some(Box::new(menu)),
                tooltip: Some(crate::version::NAME.to_string()),
                menu_on_left_click: false,
                menu_on_right_click: true,
                ..Default::default()
            })
            .map_err(|error| error.to_string())?;
            Ok(Self { _icon: icon })
        }

        /// The menu's and icon's events, which `muda` and `tray-icon` post from
        /// wherever the click arrived and this thread reads.
        pub(super) fn drain(&self) -> Vec<TrayEvent> {
            let mut events: Vec<TrayEvent> = MenuEvent::receiver()
                .try_iter()
                .filter_map(|event| match event.id.0.as_str() {
                    SHOW => Some(TrayEvent::Show),
                    QUIT => Some(TrayEvent::Quit),
                    _ => None,
                })
                .collect();

            for event in TrayIconEvent::receiver().try_iter() {
                match event {
                    TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    }
                    | TrayIconEvent::DoubleClick {
                        button: MouseButton::Left,
                        ..
                    } => {
                        events.push(TrayEvent::Show);
                    }
                    _ => {}
                }
            }

            events.dedup();
            events
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The asset is the icon, at the size the code assumes. A truncated file, or
    /// a blank one, would be an invisible tray icon or a panic inside a backend -
    /// and both would look like a desktop problem rather than a build one.
    #[test]
    fn the_asset_is_a_square_of_pixels_with_a_shape_in_it() {
        assert_eq!(PIXELS.len(), (SIDE * SIDE * 4) as usize);
        let (pixels, leftover) = PIXELS.as_chunks::<4>();
        assert!(leftover.is_empty(), "the asset is whole pixels");
        assert!(
            pixels.iter().any(|pixel| pixel[3] == 255),
            "the icon has an opaque middle"
        );
        assert!(
            pixels.iter().any(|pixel| pixel[3] == 0),
            "the icon is a shape: its corners are transparent"
        );
    }

    #[test]
    fn tray_labels_are_translated_and_distinct() {
        for lang in crate::text::Lang::ALL {
            let t = crate::text::text(lang);
            assert!(!t.tray_show.trim().is_empty());
            assert!(!t.tray_quit.trim().is_empty());
            assert_ne!(t.tray_show, t.tray_quit);
        }
        let en = crate::text::text(crate::text::Lang::En);
        let zh = crate::text::text(crate::text::Lang::Zh);
        assert_eq!(en.tray_show, "Open window");
        assert_eq!(en.tray_quit, "Quit completely");
        assert_eq!(zh.tray_show, "打开窗口");
        assert_eq!(zh.tray_quit, "完全退出");
    }

    #[test]
    fn fake_tray_starts_and_drains_events() {
        let (tray, sender) = testing::fake_tray();
        assert!(tray.drain().is_empty());
        sender.send(TrayEvent::Show).unwrap();
        sender.send(TrayEvent::Quit).unwrap();
        assert_eq!(tray.drain(), vec![TrayEvent::Show, TrayEvent::Quit]);
        assert!(tray.drain().is_empty());
    }
}
